name = "data-mcky-space"
compatibility_date = "2026-07-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[vars]
R2_PUBLIC_URL = "https://pub-462db07575b84a13b83ba0f2632f6ec2.r2.dev"
