import { readFileSync, existsSync } from 'node:fs'
import assert from 'node:assert/strict'
const read = p => readFileSync(p, 'utf8')
const html = read('dist/index.html')
const links = [...html.matchAll(/<link\b[^>]*rel=["']manifest["'][^>]*>/g)]
assert.equal(links.length, 1, 'Exactly one manifest link')
assert.match(links[0][0], /manifest\.json/)
const m = JSON.parse(read('dist/manifest.json'))
assert.equal(m.id, '/')
assert.equal(m.scope, '/')
assert.match(m.description, /ลูกค้า|customer|client/i)
assert.doesNotMatch(m.description, /shift|driver/i)
for (const icon of m.icons) assert.ok(existsSync(`dist${icon.src}`), icon.src)
const maskable = m.icons.find(i => i.purpose === 'maskable')
assert.ok(maskable, 'A maskable icon entry exists')
const { execSync } = await import('node:child_process')
const dims = execSync(`file dist${maskable.src}`).toString()
assert.match(dims, /512 x 512/, 'Maskable icon is genuinely 512x512')
const sw = read('dist/sw.js')
assert.doesNotMatch(sw, /NetworkFirst|api-cache|r2-images/, 'No API/image runtime caching in generated SW')
assert.match(sw, /sw-cleanup\.js/)
assert.match(sw, /allowlist/)
assert.ok(!existsSync('dist/registerSW.js'), 'Only application registers service worker')
assert.ok(!existsSync('dist/manifest.webmanifest'), 'No duplicate manifest output')
assert.equal(read('dist/_routes.json'), read('public/_routes.json'))
const pkg = JSON.parse(read('package.json'))
assert.ok(!pkg.scripts.postbuild, 'Build must not copy dist back into sources')
console.log('PASS: single manifest, correct app identity, static-only SW, one registration, routes preserved')
